---
version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    reviewers:
      - "miguelmartens"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    schedule:
      interval: "daily"
    directory: "/"
    reviewers:
      - "miguelmartens"
    groups:
      deps:
        patterns:
          - "*"
