[package]
name = "zed-base64-slash-command"
version = "0.0.1"
edition = "2024"

[lib]
path = "src/base64-slash-command.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.3.0"
base64 = "0.22.1"
